export interface CountryCurrency {
  country: string;
  currency: string;
}

export const COUNTRIES_AND_CURRENCIES: CountryCurrency[] = [
  { country: "Afghanistan", currency: "AFN (؋) — Afghan Afghani" },
  { country: "Albania", currency: "ALL (L) — Albanian Lek" },
  { country: "Algeria", currency: "DZD (دج) — Algerian Dinar" },
  { country: "Andorra", currency: "EUR (€) — Euro" },
  { country: "Angola", currency: "AOA (Kz) — Angolan Kwanza" },
  { country: "Antigua and Barbuda", currency: "XCD ($) — East Caribbean Dollar" },
  { country: "Argentina", currency: "ARS ($) — Argentine Peso" },
  { country: "Armenia", currency: "AMD (֏) — Armenian Dram" },
  { country: "Australia", currency: "AUD ($) — Australian Dollar" },
  { country: "Austria", currency: "EUR (€) — Euro" },
  { country: "Azerbaijan", currency: "AZN (₼) — Azerbaijani Manat" },
  { country: "Bahamas", currency: "BSD ($) — Bahamian Dollar" },
  { country: "Bahrain", currency: "BHD (.د.ب) — Bahraini Dinar" },
  { country: "Bangladesh", currency: "BDT (৳) — Bangladeshi Taka" },
  { country: "Barbados", currency: "BBD ($) — Barbadian Dollar" },
  { country: "Belarus", currency: "BYN (Br) — Belarusian Ruble" },
  { country: "Belgium", currency: "EUR (€) — Euro" },
  { country: "Belize", currency: "BZD ($) — Belize Dollar" },
  { country: "Benin", currency: "XOF (Fr) — West African CFA franc" },
  { country: "Bhutan", currency: "BTN (Nu.) — Bhutanese Ngultrum" },
  { country: "Bolivia", currency: "BOB (Bs.) — Bolivian Boliviano" },
  { country: "Bosnia and Herzegovina", currency: "BAM (KM) — Bosnia and Herzegovina Convertible Mark" },
  { country: "Botswana", currency: "BWP (P) — Botswana Pula" },
  { country: "Brazil", currency: "BRL (R$) — Brazilian Real" },
  { country: "Brunei", currency: "BND ($) — Brunei Dollar" },
  { country: "Bulgaria", currency: "BGN (лв) — Bulgarian Lev" },
  { country: "Burkina Faso", currency: "XOF (Fr) — West African CFA franc" },
  { country: "Burundi", currency: "BIF (Fr) — Burundian Franc" },
  { country: "Cabo Verde", currency: "CVE (Esc) — Cape Verdean Escudo" },
  { country: "Cambodia", currency: "KHR (៛) — Cambodian Riel" },
  { country: "Cameroon", currency: "XAF (Fr) — Central African CFA franc" },
  { country: "Canada", currency: "CAD ($) — Canadian Dollar" },
  { country: "Central African Republic", currency: "XAF (Fr) — Central African CFA franc" },
  { country: "Chad", currency: "XAF (Fr) — Central African CFA franc" },
  { country: "Chile", currency: "CLP ($) — Chilean Peso" },
  { country: "China", currency: "CNY (¥) — Chinese Yuan" },
  { country: "Colombia", currency: "COP ($) — Colombian Peso" },
  { country: "Comoros", currency: "KMF (Fr) — Comorian Franc" },
  { country: "Congo, Democratic Republic of the", currency: "CDF (Fr) — Congolese Franc" },
  { country: "Congo, Republic of the", currency: "XAF (Fr) — Central African CFA franc" },
  { country: "Costa Rica", currency: "CRC (₡) — Costa Rican Colón" },
  { country: "Côte d'Ivoire", currency: "XOF (Fr) — West African CFA franc" },
  { country: "Croatia", currency: "EUR (€) — Euro" },
  { country: "Cuba", currency: "CUP ($) — Cuban Peso" },
  { country: "Cyprus", currency: "EUR (€) — Euro" },
  { country: "Czech Republic", currency: "CZK (Kč) — Czech Koruna" },
  { country: "Denmark", currency: "DKK (kr) — Danish Krone" },
  { country: "Djibouti", currency: "DJF (Fr) — Djiboutian Franc" },
  { country: "Dominica", currency: "XCD ($) — East Caribbean Dollar" },
  { country: "Dominican Republic", currency: "DOP ($) — Dominican Peso" },
  { country: "Ecuador", currency: "USD ($) — US Dollar" },
  { country: "Egypt", currency: "EGP (£) — Egyptian Pound" },
  { country: "El Salvador", currency: "USD ($) — US Dollar" },
  { country: "Equatorial Guinea", currency: "XAF (Fr) — Central African CFA franc" },
  { country: "Eritrea", currency: "ERN (Nfk) — Eritrean Nakfa" },
  { country: "Estonia", currency: "EUR (€) — Euro" },
  { country: "Eswatini", currency: "SZL (L) — Eswatini Lilangeni" },
  { country: "Ethiopia", currency: "ETB (Br) — Ethiopian Birr" },
  { country: "Fiji", currency: "FJD ($) — Fijian Dollar" },
  { country: "Finland", currency: "EUR (€) — Euro" },
  { country: "France", currency: "EUR (€) — Euro" },
  { country: "Gabon", currency: "XAF (Fr) — Central African CFA franc" },
  { country: "Gambia", currency: "GMD (D) — Gambian Dalasi" },
  { country: "Georgia", currency: "GEL (₾) — Georgian Lari" },
  { country: "Germany", currency: "EUR (€) — Euro" },
  { country: "Ghana", currency: "GHS (₵) — Ghanaian Cedi" },
  { country: "Greece", currency: "EUR (€) — Euro" },
  { country: "Grenada", currency: "XCD ($) — East Caribbean Dollar" },
  { country: "Guatemala", currency: "GTQ (Q) — Guatemalan Quetzal" },
  { country: "Guinea", currency: "GNF (Fr) — Guinean Franc" },
  { country: "Guinea-Bissau", currency: "XOF (Fr) — West African CFA franc" },
  { country: "Guyana", currency: "GYD ($) — Guyanese Dollar" },
  { country: "Haiti", currency: "HTG (G) — Haitian Gourde" },
  { country: "Honduras", currency: "HNL (L) — Honduran Lempira" },
  { country: "Hungary", currency: "HUF (Ft) — Hungarian Forint" },
  { country: "Iceland", currency: "ISK (kr) — Icelandic Króna" },
  { country: "India", currency: "INR (₹) — Indian Rupee" },
  { country: "Indonesia", currency: "IDR (Rp) — Indonesian Rupiah" },
  { country: "Iran", currency: "IRR (﷼) — Iranian Rial" },
  { country: "Iraq", currency: "IQD (ع.د) — Iraqi Dinar" },
  { country: "Ireland", currency: "EUR (€) — Euro" },
  { country: "Israel", currency: "ILS (₪) — Israeli New Shekel" },
  { country: "Italy", currency: "EUR (€) — Euro" },
  { country: "Jamaica", currency: "JMD ($) — Jamaican Dollar" },
  { country: "Japan", currency: "JPY (¥) — Japanese Yen" },
  { country: "Jordan", currency: "JOD (د.أ) — Jordanian Dinar" },
  { country: "Kazakhstan", currency: "KZT (₸) — Kazakhstani Tenge" },
  { country: "Kenya", currency: "KES (Sh) — Kenyan Shilling" },
  { country: "Kiribati", currency: "AUD ($) — Australian Dollar" },
  { country: "Korea, North", currency: "KPW (₩) — North Korean Won" },
  { country: "Korea, South", currency: "KRW (₩) — South Korean Won" },
  { country: "Kuwait", currency: "KWD (د.ك) — Kuwaiti Dinar" },
  { country: "Kyrgyzstan", currency: "KGS (с) — Kyrgyzstani Som" },
  { country: "Laos", currency: "LAK (₭) — Lao Kip" },
  { country: "Latvia", currency: "EUR (€) — Euro" },
  { country: "Lebanon", currency: "LBP (£) — Lebanese Pound" },
  { country: "Lesotho", currency: "LSL (L) — Lesotho Loti" },
  { country: "Liberia", currency: "LRD ($) — Liberian Dollar" },
  { country: "Libya", currency: "LYD (ل.د) — Libyan Dinar" },
  { country: "Liechtenstein", currency: "CHF (Fr) — Swiss Franc" },
  { country: "Lithuania", currency: "EUR (€) — Euro" },
  { country: "Luxembourg", currency: "EUR (€) — Euro" },
  { country: "Madagascar", currency: "MGA (Ar) — Malagasy Ariary" },
  { country: "Malawi", currency: "MWK (MK) — Malawian Kwacha" },
  { country: "Malaysia", currency: "MYR (RM) — Malaysian Ringgit" },
  { country: "Maldives", currency: "MVR (.ރ) — Maldivian Rufiyaa" },
  { country: "Mali", currency: "XOF (Fr) — West African CFA franc" },
  { country: "Malta", currency: "EUR (€) — Euro" },
  { country: "Marshall Islands", currency: "USD ($) — US Dollar" },
  { country: "Mauritania", currency: "MRU (UM) — Mauritanian Ouguiya" },
  { country: "Mauritius", currency: "MUR (₨) — Mauritian Rupee" },
  { country: "Mexico", currency: "MXN ($) — Mexican Peso" },
  { country: "Micronesia", currency: "USD ($) — US Dollar" },
  { country: "Moldova", currency: "MDL (L) — Moldovan Leu" },
  { country: "Monaco", currency: "EUR (€) — Euro" },
  { country: "Mongolia", currency: "MNT (₮) — Mongolian Tögrög" },
  { country: "Montenegro", currency: "EUR (€) — Euro" },
  { country: "Morocco", currency: "MAD (د.م.) — Moroccan Dirham" },
  { country: "Mozambique", currency: "MZN (MT) — Mozambican Metical" },
  { country: "Myanmar", currency: "MMK (Ks) — Myanmar Kyat" },
  { country: "Namibia", currency: "NAD ($) — Namibian Dollar" },
  { country: "Nauru", currency: "AUD ($) — Australian Dollar" },
  { country: "Nepal", currency: "NPR (रू) — Nepalese Rupee" },
  { country: "Netherlands", currency: "EUR (€) — Euro" },
  { country: "New Zealand", currency: "NZD ($) — New Zealand Dollar" },
  { country: "Nicaragua", currency: "NIO (C$) — Nicaraguan Córdoba" },
  { country: "Niger", currency: "XOF (Fr) — West African CFA franc" },
  { country: "Nigeria", currency: "NGN (₦) — Nigerian Naira" },
  { country: "North Macedonia", currency: "MKD (ден) — Macedonian Denar" },
  { country: "Norway", currency: "NOK (kr) — Norwegian Krone" },
  { country: "Oman", currency: "OMR (ر.ع.) — Omani Rial" },
  { country: "Pakistan", currency: "PKR (₨) — Pakistani Rupee" },
  { country: "Palau", currency: "USD ($) — US Dollar" },
  { country: "Panama", currency: "PAB (B/.) — Panamanian Balboa" },
  { country: "Papua New Guinea", currency: "PGK (K) — Papua New Guinean Kina" },
  { country: "Paraguay", currency: "PYG (₲) — Paraguayan Guaraní" },
  { country: "Peru", currency: "PEN (S/.) — Peruvian Sol" },
  { country: "Philippines", currency: "PHP (₱) — Philippine Peso" },
  { country: "Poland", currency: "PLN (zł) — Polish Złoty" },
  { country: "Portugal", currency: "EUR (€) — Euro" },
  { country: "Qatar", currency: "QAR (ر.ق) — Qatari Riyal" },
  { country: "Romania", currency: "RON (lei) — Romanian Leu" },
  { country: "Russia", currency: "RUB (₽) — Russian Ruble" },
  { country: "Rwanda", currency: "RWF (Fr) — Rwandan Franc" },
  { country: "Saint Kitts and Nevis", currency: "XCD ($) — East Caribbean Dollar" },
  { country: "Saint Lucia", currency: "XCD ($) — East Caribbean Dollar" },
  { country: "Saint Vincent and the Grenadines", currency: "XCD ($) — East Caribbean Dollar" },
  { country: "Samoa", currency: "WST (T) — Samoan Tālā" },
  { country: "San Marino", currency: "EUR (€) — Euro" },
  { country: "Sao Tome and Principe", currency: "STN (Db) — São Tomé and Príncipe Dobra" },
  { country: "Saudi Arabia", currency: "SAR (ر.س) — Saudi Riyal" },
  { country: "Senegal", currency: "XOF (Fr) — West African CFA franc" },
  { country: "Serbia", currency: "RSD (дин) — Serbian Dinar" },
  { country: "Seychelles", currency: "SCR (₨) — Seychellois Rupee" },
  { country: "Sierra Leone", currency: "SLL (Le) — Sierra Leonean Leone" },
  { country: "Singapore", currency: "SGD ($) — Singapore Dollar" },
  { country: "Slovakia", currency: "EUR (€) — Euro" },
  { country: "Slovenia", currency: "EUR (€) — Euro" },
  { country: "Solomon Islands", currency: "SBD ($) — Solomon Islands Dollar" },
  { country: "Somalia", currency: "SOS (Sh) — Somali Shilling" },
  { country: "South Africa", currency: "ZAR (R) — South African Rand" },
  { country: "South Sudan", currency: "SSP (£) — South Sudanese Pound" },
  { country: "Spain", currency: "EUR (€) — Euro" },
  { country: "Sri Lanka", currency: "LKR (Rs) — Sri Lankan Rupee" },
  { country: "Sudan", currency: "SDG (£) — Sudanese Pound" },
  { country: "Suriname", currency: "SRD ($) — Surinamese Dollar" },
  { country: "Sweden", currency: "SEK (kr) — Swedish Krona" },
  { country: "Switzerland", currency: "CHF (Fr) — Swiss Franc" },
  { country: "Syria", currency: "SYP (£) — Syrian Pound" },
  { country: "Taiwan", currency: "TWD ($) — New Taiwan Dollar" },
  { country: "Tajikistan", currency: "TJS (SM) — Tajikistani Somoni" },
  { country: "Tanzania", currency: "TZS (Sh) — Tanzanian Shilling" },
  { country: "Thailand", currency: "THB (฿) — Thai Baht" },
  { country: "Timor-Leste", currency: "USD ($) — US Dollar" },
  { country: "Togo", currency: "XOF (Fr) — West African CFA franc" },
  { country: "Tonga", currency: "TOP (T$) — Tongan Paʻanga" },
  { country: "Trinidad and Tobago", currency: "TTD ($) — Trinidad and Tobago Dollar" },
  { country: "Tunisia", currency: "TND (د.ت) — Tunisian Dinar" },
  { country: "Turkey", currency: "TRY (₺) — Turkish Lira" },
  { country: "Turkmenistan", currency: "TMT (m) — Turkmenistani Manat" },
  { country: "Tuvalu", currency: "AUD ($) — Australian Dollar" },
  { country: "Uganda", currency: "UGX (Sh) — Ugandan Shilling" },
  { country: "Ukraine", currency: "UAH (₴) — Ukrainian Hryvnia" },
  { country: "United Arab Emirates", currency: "AED (د.إ) — United Arab Emirates Dirham" },
  { country: "United Kingdom", currency: "GBP (£) — British Pound" },
  { country: "United States", currency: "USD ($) — US Dollar" },
  { country: "Uruguay", currency: "UYU ($) — Uruguayan Peso" },
  { country: "Uzbekistan", currency: "UZS (so'm) — Uzbekistani Som" },
  { country: "Vanuatu", currency: "VUV (Vt) — Vanuatu Vatu" },
  { country: "Vatican City", currency: "EUR (€) — Euro" },
  { country: "Venezuela", currency: "VES (Bs.S) — Venezuelan Bolívar" },
  { country: "Vietnam", currency: "VND (₫) — Vietnamese Đồng" },
  { country: "Yemen", currency: "YER (﷼) — Yemeni Rial" },
  { country: "Zambia", currency: "ZMW (ZK) — Zambian Kwacha" },
  { country: "Zimbabwe", currency: "ZWL ($) — Zimbabwean Dollar" }
];

export const ALL_CURRENCIES = Array.from(new Set(COUNTRIES_AND_CURRENCIES.map(item => item.currency)));
